services:
  krab:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: krab
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: s225096
      POSTGRES_PASSWORD: krab
